### ISSUE TITLE
internal/fs error

### ISSUE THREAD

**Issue by mr-woot** [coryhouse/react-flux-starter-kit#12]
Tushar:react-flux-starter-kit mr-woot$ gulp
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users/mr-woot/Desktop/react-flux-starter-kit/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by coryhouse** [comment]
1. Does this occur with the final course exercise? 
2. What version of Node are you on? 
3. What is your OS?
4. What command line are you using?
5. Are you installing via npm or yarn?

**Comment by mr-woot** [comment]
You may close this issue, I hacked around the web and came to know that this issue arises due to graceful-fs compatibility. I changed the node version from v7 to v6 and it worked smoothly but shows a DEPRECATED warning.

My System Info:
OS:                   MacOS Sierra
Node Version:  v7.3
cmd line:           iterm2
installing via npm

**Comment by Bullrich** [comment]
@mr-woot could you share how you resolve this issue? I'm stuck with the same error.

**Comment by joeldeng** [comment]
Sounds like there are plenty of problems with Node v7

It can also be circumvented by running npm install gulp after npm install, it works well, but then, you have to install eslint-config-default to get it to work at all. 

My issue comes right after that, where I get an error saying module babel-eslint could not be found. 

```
[17:42:23] Server started http://localhost:9005
[17:42:23] LiveReload started on port 35729
[17:42:23]
...\React-Flux-Starter\src\main.js
  0:0  error  Cannot find module 'babel-eslint'

✖ 1 problem (1 error, 0 warnings)

[17:42:23] Finished 'lint' after 455 ms
[17:42:23] Starting 'default'...
[17:42:23] Finished 'default' after 33 μs
[17:42:23] Opening http://localhost:9005/ using the default OS app
```

 I run npm install babel-eslint and then nothing works.  I get the following error:

```
[17:53:17] Server started http://localhost:9005
[17:53:17] LiveReload started on port 35729
C:\OneDrive\OneDrive - UW Office 365\Code\Sandbox\React-Flux-Starter\node_modules\gulp-eslint\node_modules\eslint\lib\eslint.js:642
                        throw ex;
                        ^

TypeError: Error while loading rule 'react/display-name': ruleCreator is not a function
    at C:\OneDrive\OneDrive - UW Office 365\Code\Sandbox\React-Flux-Starter\node_modules\gulp-eslint\node_modules\eslint\lib\eslint.js:628:32
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (C:\OneDrive\OneDrive - UW Office 365\Code\Sandbox\React-Flux-Starter\node_modules\gulp-eslint\node_modules\eslint\lib\eslint.js:619:16)
    at processText (C:\OneDrive\OneDrive - UW Office 365\Code\Sandbox\React-Flux-Starter\node_modules\gulp-eslint\node_modules\eslint\lib\cli-engine.js:201:27)
    at CLIEngine.executeOnText (C:\OneDrive\OneDrive - UW Office 365\Code\Sandbox\React-Flux-Starter\node_modules\gulp-eslint\node_modules\eslint\lib\cli-engine.js:361:26)
    at verify (C:\OneDrive\OneDrive - UW Office 365\Code\Sandbox\React-Flux-Starter\node_modules\gulp-eslint\index.js:19:17)
    at Transform._transform (C:\OneDrive\OneDrive - UW Office 365\Code\Sandbox\React-Flux-Starter\node_modules\gulp-eslint\index.js:37:18)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
```
Any thoughts?

From questions in previous comment:

Does this occur with the final course exercise?
This occurs on setting up the initial build process

What version of Node are you on?
v7

What is your OS?
OS: Windows 10

What command line are you using?
Windows cmd Shell 

Are you installing via npm or yarn?
npm

**Comment by coryhouse** [comment]
Hi Joel - To follow along, you need to install the versions I used in the course. If you pull down the completed course exercise, does it run for you?

**Comment by joeldeng** [comment]
Fixed the issue by realizing that there is a "closed issues" section that has an incredibly helpful section on the eslint solution deleting the .eslintrc file under my user dir.  It might be helpful to put that in the original instructions.

**Comment by coryhouse** [comment]
The course has been updated as of 6/2019 so this is no longer relevant.
