### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by sudeeptm** [coryhouse/react-flux-starter-kit#14]
While working on module 2 section Demo: Browserify Configuration, the gulp tasks fails to start. The console logs the error

[17:37:08] Using gulpfile D:\Code\pluralsight\react\react-flux\gulpfile.js
[17:37:08] Starting 'html'...
[17:37:09] Finished 'html' after 23 ms
[17:37:09] Starting 'js'...
[17:37:09] 'js' errored after 23 ms
[17:37:09] TypeError: dest.on is not a function
    at DestroyableTransform.Stream.pipe (internal/streams/legacy.js:30:8)
    at Gulp.<anonymous> (D:\Code\pluralsight\react\react-flux\gulpfile.js:49:10)
    at module.exports (D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\index.js:214:10)
    at D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\index.js:279:18
    at finish (D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\lib\runTask.js:60:3)
    at Gulp.Orchestrator._runTask (D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Code\pluralsight\react\react-flux\node_modules\orchestrator\index.js:214:10)

**Comment by coryhouse** [comment]
Looks like you might have a typo in your gulpfile.js. I'd search for dest.on. 

Or, perhaps you're just not running the versions I utilize in the course?
