### ISSUE TITLE
cant get gulp to run

### ISSUE THREAD

**Issue by adamperlis** [coryhouse/react-flux-starter-kit#3]
Hey man thanks for pulling this great repo together. Trying to get this to work. Any ideas why i might be having a problem?

`$ gulp
[12:57:32] Using gulpfile ~/code/react-flux-starter-kit/gulpfile.js
[12:57:32] Starting 'html'...
[12:57:32] Finished 'html' after 7.27 ms
[12:57:32] Starting 'js'...
[12:57:32] Finished 'js' after 23 ms
[12:57:32] Starting 'css'...
[12:57:32] Finished 'css' after 15 ms
[12:57:32] Starting 'lint'...
[12:57:32] Starting 'connect'...
[12:57:32] Finished 'connect' after 10 ms
[12:57:32] Starting 'open'...
[12:57:32] Finished 'open' after 2.78 ms
[12:57:32] Starting 'watch'...
[12:57:32] Finished 'watch' after 13 ms
[12:57:32] Server started http://localhost:9005
[12:57:32] LiveReload started on port 35729

/Users/myusername/code/react-flux-starter-kit/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:129
                    throw e;
                    ^
YAMLException: Cannot read config file: /Users/myusername/code/react-flux-starter-kit/node_modules/eslint-config-airbnb/rules/react.js
Error: end of the stream or a document separator is expected at line 2, column 12:
      'plugins': [
               ^
Referenced from: eslint-config-airbnb
Referenced from: /Users/myusername/.eslintrc
    at generateError (/Users/myusername/code/react-flux-starter-kit/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/myusername/code/react-flux-starter-kit/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readDocument (/Users/myusername/code/react-flux-starter-kit/node_modules/js-yaml/lib/js-yaml/loader.js:1508:5)
    at loadDocuments (/Users/myusername/code/react-flux-starter-kit/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/Users/myusername/code/react-flux-starter-kit/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/Users/myusername/code/react-flux-starter-kit/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
    at loadConfig (/Users/myusername/code/react-flux-starter-kit/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:73:31)
    at /Users/myusername/code/react-flux-starter-kit/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:123:46
    at Array.reduceRight (native)
    at loadConfig (/Users/myusername/code/react-flux-starter-kit/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:111:36)`

**Comment by coryhouse** [comment]
Looks like you've pulled in rules that aren't part of this kit. eslint-config-airbnb is the problem.
